/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for classes com_lxz_common_second_ndk_jninative_JNI */

#ifndef _Included_com_lxz_common_second_ndk_jninative_JNI
#define _Included_com_lxz_common_second_ndk_jninative_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    helloFromC1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_helloFromC1
  (JNIEnv *, jclass);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessStaticField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessStaticMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_lxz_common_second_ndk_jninative_JNI
 * Method:    accessParentMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lxz_common_second_ndk_jninative_JNI_accessParentMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
